# Generated by Django 5.0.7 on 2024-09-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_autor_libro_prestamo_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
    ]
